// src/monitoring/presentation/views/iot-monitoring.vue
<script setup>
import { ref, computed } from 'vue';
import { useI18n } from 'vue-i18n';
import { useIotStore } from '@/monitoring/application/iot.store.js';
import { IotStatus } from '@/monitoring/domain/model/iot.entity.js';

const { t } = useI18n();
const store = useIotStore();

const search        = ref('');
const filterStatus  = ref('');

const filteredDevices = computed(() => {
  let list = store.devices;
  const q = search.value.toLowerCase().trim();
  if (q) list = list.filter(d => d.location.toLowerCase().includes(q) || d.macAddress.toLowerCase().includes(q));
  if (filterStatus.value) list = list.filter(d => d.status === filterStatus.value);
  return list;
});

function sensorId(d)    { return `SEN-${String(d.id).padStart(3, '0')}`; }
function statusIcon(s)  { return s === IotStatus.ONLINE ? 'wifi' : s === IotStatus.OFFLINE ? 'wifi_off' : 'warning'; }
function statusClass(s) { return s === IotStatus.ONLINE ? 'green' : s === IotStatus.OFFLINE ? 'red' : 'amber'; }
function batteryIcon(b) { return b > 60 ? 'battery_full' : b > 20 ? 'battery_3_bar' : 'battery_alert'; }
function batteryClass(b){ return b > 60 ? 'green' : b > 20 ? 'amber' : 'red'; }
</script>

<template>
  <div class="page">
    <div class="page__header">
      <h1 class="page__title">{{ t('iot.title') }}</h1>
      <button class="btn btn--outline" @click="store.loadDevices()"><span class="material-icons" style="font-size:16px">refresh</span> {{ t('iot.actions.refresh') }}</button>
    </div>

    <div class="kpi-row">
      <div class="kpi-card card"><span class="material-icons kpi-icon" style="color:var(--green)">wifi</span><div><p class="kpi-label">{{ t('iot.stats.online') }}</p><p class="kpi-val">{{ store.onlineCount }}</p></div></div>
      <div class="kpi-card card"><span class="material-icons kpi-icon" style="color:var(--red)">wifi_off</span><div><p class="kpi-label">{{ t('iot.stats.offline') }}</p><p class="kpi-val kpi-val--red">{{ store.offlineCount }}</p></div></div>
      <div class="kpi-card card"><span class="material-icons kpi-icon" style="color:var(--accent)">battery_3_bar</span><div><p class="kpi-label">{{ t('iot.stats.avgBattery') }}</p><p class="kpi-val">{{ store.avgBattery }}%</p></div></div>
      <div class="kpi-card card"><span class="material-icons kpi-icon" style="color:var(--red)">notifications_active</span><div><p class="kpi-label">{{ t('iot.stats.activeAlerts') }}</p><p class="kpi-val kpi-val--red">{{ store.activeAlerts.length }}</p></div></div>
    </div>

    <div class="filters card">
      <input v-model="search" :placeholder="t('iot.search')" style="flex:1" />
      <select v-model="filterStatus">
        <option value="">{{ t('iot.filter.allStatuses') }}</option>
        <option v-for="s in Object.values(IotStatus)" :key="s" :value="s">{{ s }}</option>
      </select>
    </div>

    <div class="card" style="padding:0;overflow:hidden">
      <table class="data-table">
        <thead><tr>
          <th>{{ t('iot.table.id') }}</th><th>{{ t('iot.table.location') }}</th>
          <th>{{ t('iot.table.status') }}</th><th>{{ t('iot.table.battery') }}</th>
          <th>{{ t('iot.table.signal') }}</th><th>{{ t('iot.table.firmware') }}</th>
          <th>{{ t('iot.table.lastPing') }}</th>
        </tr></thead>
        <tbody>
          <tr v-if="!filteredDevices.length"><td colspan="7" class="table-empty">{{ t('iot.table.noData') }}</td></tr>
          <tr v-for="d in filteredDevices" :key="d.id">
            <td class="cell-id">{{ sensorId(d) }}</td>
            <td>{{ d.location }}</td>
            <td><span class="status-chip" :class="`status-chip--${statusClass(d.status)}`"><span class="material-icons" style="font-size:14px">{{ statusIcon(d.status) }}</span> {{ t('iot.status.' + d.status) }}</span></td>
            <td><span :class="`bat-${batteryClass(d.batteryLevel)}`"><span class="material-icons" style="font-size:14px">{{ batteryIcon(d.batteryLevel) }}</span> {{ d.batteryLevel }}%</span></td>
            <td>{{ d.signalStrength }} dBm</td>
            <td>{{ d.firmwareVersion }}</td>
            <td style="font-size:0.75rem;color:var(--text-secondary)">{{ d.lastHeartbeat }}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div v-if="store.activeAlerts.length" class="alerts-card card">
      <h2 class="chart-title">{{ t('iot.alerts.title') }}</h2>
      <div v-for="d in store.activeAlerts" :key="d.id" class="alert-row">
        <span class="material-icons" style="color:var(--red)">{{ statusIcon(d.status) }}</span>
        <div class="alert-info"><p class="alert-name">{{ sensorId(d) }} — {{ d.location }}</p><p class="alert-sub">{{ t('iot.status.' + d.status) }}</p></div>
        <button class="btn btn--outline" style="font-size:0.75rem" @click="store.investigateAlert(d)">{{ t('iot.alerts.investigate') }}</button>
        <button class="btn btn--danger" style="font-size:0.75rem" @click="store.scheduleReplacement(d.id)">{{ t('iot.alerts.scheduleReplacement') }}</button>
      </div>
    </div>

    <div v-if="store.reconnectedDevice" class="modal-backdrop" @click="store.dismissReconnectedModal()">
      <div class="modal card" @click.stop>
        <span class="material-icons" style="font-size:2rem;color:var(--green);margin-bottom:.5rem">check_circle</span>
        <h2>{{ t('iot.modal.title') }}</h2>
        <p>{{ sensorId(store.reconnectedDevice) }}</p>
        <button class="btn btn--primary" @click="store.dismissReconnectedModal()">OK</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.kpi-row { display: grid; gap: 1rem; grid-template-columns: repeat(4, 1fr); margin-bottom: 1rem; }
.kpi-card { align-items: center; display: flex; gap: 1rem; }
.kpi-icon { font-size: 2rem; }
.kpi-label { color: var(--text-secondary); font-size: 0.8rem; }
.kpi-val { font-size: 1.75rem; font-weight: 700; }
.kpi-val--red { color: var(--red); }
.filters { display: flex; gap: .75rem; margin-bottom: 1rem; }
.data-table { border-collapse: collapse; font-size: 0.82rem; width: 100%; }
.data-table th { background: var(--bg-surface); border-bottom: 1px solid var(--border); color: var(--text-secondary); font-weight: 500; padding: .5rem .75rem; text-align: left; }
.data-table td { border-bottom: 1px solid rgba(255,255,255,.04); padding: .5rem .75rem; }
.cell-id { color: var(--accent); font-family: monospace; }
.table-empty { color: var(--text-secondary); padding: 1.5rem; text-align: center; }
.status-chip { align-items: center; border-radius: 999px; display: inline-flex; font-size: 0.72rem; font-weight: 600; gap: 3px; padding: 2px 8px; }
.status-chip--green { background: rgba(34,197,94,.15); color: var(--green); }
.status-chip--red   { background: rgba(239,68,68,.15);  color: var(--red); }
.status-chip--amber { background: rgba(245,188,54,.15); color: var(--accent); }
.bat-green { color: var(--green); } .bat-amber { color: var(--accent); } .bat-red { color: var(--red); }
.alerts-card { margin-top: 1rem; }
.chart-title { font-size: 0.9rem; font-weight: 600; margin-bottom: .75rem; }
.alert-row { align-items: center; border-bottom: 1px solid var(--border); display: flex; gap: .75rem; padding: .5rem 0; }
.alert-info { flex: 1; }
.alert-name { font-size: 0.82rem; font-weight: 500; }
.alert-sub  { color: var(--text-secondary); font-size: 0.75rem; }
.modal-backdrop { align-items: center; background: rgba(0,0,0,.6); bottom: 0; display: flex; justify-content: center; left: 0; position: fixed; right: 0; top: 0; z-index: 400; }
.modal { align-items: center; display: flex; flex-direction: column; gap: .5rem; max-width: 320px; padding: 2rem; text-align: center; }
@media (max-width: 900px) { .kpi-row { grid-template-columns: repeat(2, 1fr); } }
</style>

// src/app/iot/presentation/views/iot-monitoring.component.ts
import { Component, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { MatTableModule } from '@angular/material/table';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { FormsModule } from '@angular/forms';
import { IotStore } from '../../application/iot.store';
import { Iot, IotStatus } from '../../domain/model/iot.entity';

@Component({
  selector: 'app-iot-monitoring',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    TranslateModule,
    MatTableModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatSelectModule,
  ],
  templateUrl: './iot-monitoring.component.html',
  styleUrl: './iot-monitoring.component.scss',
})
export class IotMonitoringComponent {
  private store = inject(IotStore);

  readonly IotStatus = IotStatus;
  readonly displayedColumns = [
    'id', 'equipmentId', 'location', 'status',
    'lastHeartbeat', 'batteryLevel', 'signalStrength', 'firmwareVersion',
  ];

  readonly isLoading        = this.store.loading;
  readonly deviceCount      = this.store.deviceCount;
  readonly onlineCount      = this.store.onlineCount;
  readonly offlineCount     = this.store.offlineCount;
  readonly avgBattery       = this.store.avgBattery;
  readonly activeAlerts     = this.store.activeAlerts;
  readonly reconnectedDevice = this.store.reconnectedDevice;

  searchQuery  = signal('');
  statusFilter = signal<IotStatus | ''>('');

  readonly filteredDevices = computed(() => {
    const q      = this.searchQuery().toLowerCase();
    const status = this.statusFilter();
    return this.store.devices().filter(d => {
      const matchesSearch =
        !q ||
        d.location.toLowerCase().includes(q) ||
        d.equipmentId.toString().includes(q) ||
        `sns-${d.id.toString().padStart(3, '0')}`.includes(q);
      const matchesStatus = !status || d.status === status;
      return matchesSearch && matchesStatus;
    });
  });

  sensorId(id: number): string {
    return `SNS-${id.toString().padStart(3, '0')}`;
  }

  statusIcon(status: IotStatus): string {
    if (status === IotStatus.ONLINE)  return 'sensors';
    if (status === IotStatus.WARNING) return 'warning';
    return 'sensors_off';
  }

  batteryIcon(level: number): string {
    if (level === 0)  return 'battery_0_bar';
    if (level < 20)   return 'battery_1_bar';
    if (level < 40)   return 'battery_2_bar';
    if (level < 60)   return 'battery_3_bar';
    if (level < 80)   return 'battery_5_bar';
    return 'battery_full';
  }

  batteryClass(level: number): string {
    if (level < 20) return 'battery--critical';
    if (level < 50) return 'battery--low';
    return 'battery--ok';
  }

  onSearchChange(v: string): void        { this.searchQuery.set(v); }
  onStatusFilterChange(v: string): void  { this.statusFilter.set(v as IotStatus | ''); }

  onRefresh(): void { this.store.refresh(); }

  onInvestigate(sensor: Iot): void { this.store.investigateAlert(sensor); }

  onScheduleReplacement(sensorId: number): void { this.store.scheduleReplacement(sensorId); }

  onDismissModal(): void { this.store.dismissReconnectedModal(); }
}

<div class="iot-page">

  <!-- Header -->
  <div class="iot-header">
    <div class="iot-header__text">
      <h1 class="iot-header__title">{{ 'iot.title' | translate }}</h1>
      <p class="iot-header__subtitle">{{ 'iot.subtitle' | translate }}</p>
    </div>
    <button class="btn-refresh" (click)="onRefresh()">
      <mat-icon>refresh</mat-icon>
      {{ 'iot.actions.refresh' | translate }}
    </button>
  </div>

  <!-- KPI Cards -->
  <div class="iot-stats">
    <div class="stat-card stat-card--online">
      <mat-icon>sensors</mat-icon>
      <div class="stat-card__info">
        <span class="stat-card__value">{{ onlineCount() }}</span>
        <span class="stat-card__label">{{ 'iot.stats.online' | translate }}</span>
        <span class="stat-card__sub">{{ 'iot.stats.ofTotal' | translate:{ total: deviceCount() } }}</span>
      </div>
    </div>
    <div class="stat-card stat-card--offline">
      <mat-icon>sensors_off</mat-icon>
      <div class="stat-card__info">
        <span class="stat-card__value">{{ offlineCount() }}</span>
        <span class="stat-card__label">{{ 'iot.stats.offline' | translate }}</span>
      </div>
    </div>
    <div class="stat-card stat-card--battery">
      <mat-icon>battery_charging_full</mat-icon>
      <div class="stat-card__info">
        <span class="stat-card__value">{{ avgBattery() }}%</span>
        <span class="stat-card__label">{{ 'iot.stats.avgBattery' | translate }}</span>
      </div>
    </div>
    <div class="stat-card" [ngClass]="activeAlerts().length > 0 ? 'stat-card--alerts' : 'stat-card--no-alerts'">
      <mat-icon>notification_important</mat-icon>
      <div class="stat-card__info">
        <span class="stat-card__value">{{ activeAlerts().length }}</span>
        <span class="stat-card__label">{{ 'iot.stats.activeAlerts' | translate }}</span>
      </div>
    </div>
  </div>

  <!-- Search + Filter -->
  <div class="iot-filters">
    <div class="iot-search">
      <mat-icon class="iot-search__icon">search</mat-icon>
      <input
        class="iot-search__input"
        type="text"
        [placeholder]="'iot.search' | translate"
        [ngModel]="searchQuery()"
        (ngModelChange)="onSearchChange($event)"
      />
    </div>
    <mat-form-field appearance="outline" class="iot-filter-select">
      <mat-label>{{ 'iot.filter.status' | translate }}</mat-label>
      <mat-select [ngModel]="statusFilter()" (ngModelChange)="onStatusFilterChange($event)">
        <mat-option value="">{{ 'iot.filter.allStatuses' | translate }}</mat-option>
        <mat-option value="ONLINE">{{ 'iot.status.ONLINE' | translate }}</mat-option>
        <mat-option value="WARNING">{{ 'iot.status.WARNING' | translate }}</mat-option>
        <mat-option value="OFFLINE">{{ 'iot.status.OFFLINE' | translate }}</mat-option>
      </mat-select>
    </mat-form-field>
  </div>

  <!-- Sensor Table -->
  <div class="iot-card">
    <div class="iot-card__header">
      <h2 class="iot-card__title">{{ 'iot.table.title' | translate }} ({{ deviceCount() }})</h2>
    </div>

    @if (isLoading()) {
      <div class="iot-loading">
        <mat-spinner diameter="48"></mat-spinner>
      </div>
    }

    <table mat-table [dataSource]="filteredDevices()" class="iot-table">

      <ng-container matColumnDef="id">
        <th mat-header-cell *matHeaderCellDef>{{ 'iot.table.id' | translate }}</th>
        <td mat-cell *matCellDef="let row"><span class="cell-id">{{ sensorId(row.id) }}</span></td>
      </ng-container>

      <ng-container matColumnDef="equipmentId">
        <th mat-header-cell *matHeaderCellDef>{{ 'iot.table.machine' | translate }}</th>
        <td mat-cell *matCellDef="let row" class="cell-secondary">M-{{ row.equipmentId.toString().padStart(3, '0') }}</td>
      </ng-container>

      <ng-container matColumnDef="location">
        <th mat-header-cell *matHeaderCellDef>{{ 'iot.table.location' | translate }}</th>
        <td mat-cell *matCellDef="let row" class="cell-secondary">{{ row.location }}</td>
      </ng-container>

      <ng-container matColumnDef="status">
        <th mat-header-cell *matHeaderCellDef>{{ 'iot.table.status' | translate }}</th>
        <td mat-cell *matCellDef="let row">
          <span class="badge" [ngClass]="{
            'badge--online':  row.status === IotStatus.ONLINE,
            'badge--offline': row.status === IotStatus.OFFLINE,
            'badge--warning': row.status === IotStatus.WARNING
          }">
            <mat-icon>{{ statusIcon(row.status) }}</mat-icon>
            {{ 'iot.status.' + row.status | translate }}
          </span>
        </td>
      </ng-container>

      <ng-container matColumnDef="lastHeartbeat">
        <th mat-header-cell *matHeaderCellDef>{{ 'iot.table.lastPing' | translate }}</th>
        <td mat-cell *matCellDef="let row" class="cell-secondary">{{ row.lastHeartbeat | date:'HH:mm:ss' }}</td>
      </ng-container>

      <ng-container matColumnDef="batteryLevel">
        <th mat-header-cell *matHeaderCellDef>{{ 'iot.table.battery' | translate }}</th>
        <td mat-cell *matCellDef="let row">
          <div class="battery-cell">
            <mat-icon [ngClass]="batteryClass(row.batteryLevel)">{{ batteryIcon(row.batteryLevel) }}</mat-icon>
            <span [ngClass]="batteryClass(row.batteryLevel)">{{ row.batteryLevel }}%</span>
          </div>
        </td>
      </ng-container>

      <ng-container matColumnDef="signalStrength">
        <th mat-header-cell *matHeaderCellDef>{{ 'iot.table.signal' | translate }}</th>
        <td mat-cell *matCellDef="let row" class="cell-secondary">{{ row.signalStrength }}%</td>
      </ng-container>

      <ng-container matColumnDef="firmwareVersion">
        <th mat-header-cell *matHeaderCellDef>{{ 'iot.table.firmware' | translate }}</th>
        <td mat-cell *matCellDef="let row"><span class="cell-firmware">{{ row.firmwareVersion }}</span></td>
      </ng-container>

      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row *matRowDef="let row; columns: displayedColumns;" class="iot-row"
          [ngClass]="row.status === IotStatus.OFFLINE ? 'iot-row--offline' : ''"></tr>

      <tr class="mat-mdc-no-data-row" *matNoDataRow>
        <td [colSpan]="displayedColumns.length" class="no-data-cell">
          <mat-icon>sensors_off</mat-icon>
          <span>{{ 'iot.table.noData' | translate }}</span>
        </td>
      </tr>

    </table>
  </div>

  <!-- Active Alerts -->
  @if (activeAlerts().length > 0) {
    <div class="alerts-card">
      <div class="alerts-card__header">
        <mat-icon class="alerts-card__icon">warning_amber</mat-icon>
        <h2 class="alerts-card__title">{{ 'iot.alerts.title' | translate }} ({{ activeAlerts().length }})</h2>
      </div>
      <div class="alerts-list">
        @for (sensor of activeAlerts(); track sensor.id) {
          <div class="alert-item" [ngClass]="sensor.status === IotStatus.OFFLINE ? 'alert-item--critical' : 'alert-item--warning'">
            <mat-icon class="alert-item__icon">
              {{ sensor.status === IotStatus.OFFLINE ? 'sensors_off' : 'battery_alert' }}
            </mat-icon>
            <div class="alert-item__content">
              <div class="alert-item__title">
                @if (sensor.status === IotStatus.OFFLINE) {
                  {{ 'iot.alerts.disconnectedTitle' | translate:{ sensor: sensorId(sensor.id) } }}
                } @else {
                  {{ 'iot.alerts.lowBatteryTitle' | translate:{ sensor: sensorId(sensor.id) } }}
                }
              </div>
              <div class="alert-item__subtitle">
                {{ sensorId(sensor.id) }} |
                @if (sensor.status === IotStatus.OFFLINE) {
                  {{ 'iot.alerts.lastPing' | translate }} {{ sensor.lastHeartbeat | date:'HH:mm' }}
                } @else {
                  {{ 'iot.alerts.battery' | translate }} {{ sensor.batteryLevel }}% | {{ 'iot.alerts.signal' | translate }} {{ sensor.signalStrength }}%
                }
              </div>
            </div>
            <span class="alert-badge" [ngClass]="sensor.status === IotStatus.OFFLINE ? 'alert-badge--critical' : 'alert-badge--warning'">
              {{ (sensor.status === IotStatus.OFFLINE ? 'iot.alerts.severity.critical' : 'iot.alerts.severity.warning') | translate }}
            </span>
            @if (sensor.status === IotStatus.OFFLINE) {
              <button class="btn-alert btn-alert--primary" (click)="onInvestigate(sensor)">
                {{ 'iot.alerts.investigate' | translate }}
              </button>
            } @else {
              <button class="btn-alert btn-alert--secondary" (click)="onScheduleReplacement(sensor.id)">
                {{ 'iot.alerts.scheduleReplacement' | translate }}
              </button>
            }
          </div>
        }
      </div>
    </div>
  }

</div>

<!-- Reconnection Modal (T04) -->
@if (reconnectedDevice()) {
  <div class="modal-overlay" (click)="onDismissModal()">
    <div class="modal" (click)="$event.stopPropagation()">
      <button class="modal__close" (click)="onDismissModal()">
        <mat-icon>close</mat-icon>
      </button>
      <div class="modal__content">
        <mat-icon class="modal__icon">check_circle</mat-icon>
        <h2 class="modal__title">{{ 'iot.modal.title' | translate }}</h2>
        <p class="modal__subtitle">
          {{ sensorId(reconnectedDevice()!.id) }} &mdash;
          M-{{ reconnectedDevice()!.equipmentId.toString().padStart(3, '0') }}
        </p>
        <p class="modal__detail">{{ reconnectedDevice()!.location }}</p>
        <button class="btn-modal" (click)="onDismissModal()">
          {{ 'iot.modal.close' | translate }}
        </button>
      </div>
    </div>
  </div>
}
